### ISSUE TITLE
Error en el registro si permite crear una cuenta cuando el correo tiene #

### ISSUE THREAD

**Issue by valia9709** [valia9709/calidadpinterest#11]
Al registrar un usuario, permite cuando se ingresa un correo que contiene "#" ejemplo "valia9709#gmail.com"

**Comment by valia9709** [comment]
https://valia.testquality.com defect [D1](https://valia.testquality.com/project/13100/result/2596488/defect/9490).

**Comment by fundacionforeverpets** [comment]
Corregido
