### ISSUE TITLE
Error al dejar se seguir a una persona, se pulsa el boton deshabilitando el seguir pero permanece habilitado

### ISSUE THREAD

**Issue by valia9709** [valia9709/calidadpinterest#13]
No permite dejar de seguir a una persona que con anterioridad se empezó a seguir

**Comment by valia9709** [comment]
https://valia.testquality.com defect [D3](https://valia.testquality.com/project/13100/result/2596493/defect/9492).

**Comment by fundacionforeverpets** [comment]
Corregido
